
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150226 (SVN rev 63)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int Tk_guion = 12;
  public static final int Tk_inicio_Ejercicios = 15;
  public static final int Tk_inicio_Conjuntos = 14;
  public static final int Tk_cer_positiva = 2;
  public static final int Tk_CONJ = 8;
  public static final int EOF = 0;
  public static final int Tk_llavec = 7;
  public static final int Tk_llavea = 6;
  public static final int Tk_kleene = 3;
  public static final int Tk_or = 4;
  public static final int error = 1;
  public static final int Tk_valor_comillas = 11;
  public static final int Tk_dosp = 17;
  public static final int Tk_id = 16;
  public static final int Tk_pcoma = 10;
  public static final int TK_inicio_ER = 13;
  public static final int Tk_flecha = 9;
  public static final int Tk_concat = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Tk_cer_positiva",
  "Tk_kleene",
  "Tk_or",
  "Tk_concat",
  "Tk_llavea",
  "Tk_llavec",
  "Tk_CONJ",
  "Tk_flecha",
  "Tk_pcoma",
  "Tk_valor_comillas",
  "Tk_guion",
  "TK_inicio_ER",
  "Tk_inicio_Conjuntos",
  "Tk_inicio_Ejercicios",
  "Tk_id",
  "Tk_dosp"
  };
}

